import { Database, MapPin, ShieldCheck } from 'lucide-react';
import { count, dateLabel, missingFieldLabel, scopeLabel, type Bootstrap } from './api';
import { Badge, Notice } from './components';

export function Sources({ data }: { data: Bootstrap }) {
  return <>
    <header className="page-heading"><div><span className="eyebrow">SURSE ȘI ACOPERIRE</span><h1>Surse și acoperire</h1><p>Catalogul și cotațiile sunt două lucruri diferite. Acoperirea este limitată la fișierele încărcate.</p></div></header>

    <div className="source-grid">{data.capabilities.sources.map((source) => <article className="source-card" key={source.id}><span className="source-card-icon"><Database size={27} aria-hidden="true" /></span><Badge>Fișiere locale</Badge><h2>{source.name}</h2><div className="source-counts"><div><strong>{count(source.product_count)}</strong><span>înregistrări de catalog</span></div><div><strong>{count(source.quote_count)}</strong><span>cotații încărcate</span></div></div><p>Înregistrările nu sunt automat produse identice validate sau oferte disponibile la cumpărare.</p></article>)}</div>
    <section aria-labelledby="areas-heading"><div className="section-heading"><h2 id="areas-heading">Zonele probelor geografice</h2></div><div className="area-grid">{data.scenarios.map((scenario) => <article className="area-card" key={scenario.id}><MapPin size={22} aria-hidden="true" /><div><h3>{scenario.name}</h3><p>{scenario.store_count} magazine · rază {scenario.radius_m / 1000} km</p><small>Punctul probei: {scenario.latitude}, {scenario.longitude}. Nu reprezintă întregul oraș.</small></div></article>)}</div><Notice title="Lista Lidl are o altă arie" tone="neutral"><p>Fișierul Lidl este o listă a sortimentului permanent la nivel de rețea. Nu dovedește stocul unui magazin din zona aleasă; data și valabilitatea individuală ale prețurilor nu sunt specificate.</p></Notice></section>
    <section className="snapshots-section" aria-labelledby="files-heading"><div className="section-heading"><h2 id="files-heading">Fișierele și proveniența lor</h2><Badge>Fără actualizare automată</Badge></div><div className="snapshot-files">{data.snapshots.map((snapshot) => <details className="disclosure snapshot-file" key={snapshot.id}><summary><span>{snapshot.filename}</span><span>{count(snapshot.row_count)} rânduri · {count(snapshot.quote_count)} cotații</span></summary><dl className="detail-grid"><div><dt>Aria declarată</dt><dd>{scopeLabel(snapshot.query_scope)}</dd></div><div><dt>Data prețului declarată de sursă</dt><dd>{dateLabel(snapshot.source_priced_at)}</dd></div><div><dt>Momentul colectării</dt><dd>{dateLabel(snapshot.retrieved_at)}</dd></div><div><dt>Informații lipsă</dt><dd>{snapshot.missing_fields.length ? snapshot.missing_fields.map(missingFieldLabel).join(' · ') : 'Vezi limitele per cotație'}</dd></div></dl>{snapshot.notes.length ? <ul>{snapshot.notes.map((value, index) => <li key={index}>{value}</li>)}</ul> : null}<p className="hash-text">SHA-256: {snapshot.sha256}</p></details>)}</div></section>
    <Notice title="Datele firmei sunt locale" tone="neutral"><p>Lista și preferințele sunt păstrate în baza de date de pe acest calculator. Accesul depinde de accesul la calculator; această versiune nu oferă autentificare pentru echipe sau acces de pe alte dispozitive.</p></Notice>
    <div className="source-integrity"><ShieldCheck size={19} aria-hidden="true" /><span>Prețurile, asocierile și condițiile necunoscute rămân vizibile; lipsa unui preț nu devine zero.</span></div>
  </>;
}
